FROM warmfusion/xoa:latest

RUN apt-get update && \
    apt-get install -y redis-server supervisor  && \
    apt-get autoremove -qq && apt-get clean && rm -rf /usr/share/doc /usr/share/man /var/log/* /tmp/*

# Lets use localhost for the config
RUN sed -i 's/xoa-redis/localhost/g' /etc/xo-server/config.yaml

COPY supervisord.conf /etc/supervisor/supervisord.conf

EXPOSE 80

CMD ["/usr/bin/supervisord"]